const locators = {
  close: "div#trendingCategoryresult>div:nth-child(1)>button:nth-child(2)",
  close2: "div#searchCategoryresult>div:nth-child(1)>div:nth-child(1)>button:nth-child(1)",
  search: "xpath=//*[@id=\"oneC_searchLanding\"]",
  select_guidewire: "div[aria-label='Guidewire Insurance Opens in a new tab']",
  username: "xpath=//*[@id=\"idp-discovery-username\"]",
  guidewire_username: "input[name='username']",
  guidewire_next: "input[value='Next']",
  clickTheElementElement: "xpath=//*[@id=\"idp-discovery-submit\"]",
  navigation: "xpath=//*[@id=\"navPanelButton\"]",
  claimcenter: "xpath=//*[@id=\"4129a2e8-9e7f-4c85-a82f-652d67b09208-categoryid\"]/div[1]/span/p",
  selectPlanet: "xpath=//input[@data-testid='environment-dropdown']",
  planet: "xpath=//li[@role='option']//span[text()='dev']",
  apply: "div#modalRoot>div:nth-child(1)>div:nth-child(1)>div:nth-child(1)>div:nth-child(1)>div:nth-child(1)>div:nth-child(3)>button:nth-child(2)",
  username2: "xpath=//input[@name='Login-LoginScreen-LoginDV-username']",
  password: "xpath=//input[@name='Login-LoginScreen-LoginDV-password']",
  clickTheElementElement2: "xpath=//div[@role='button']//div[@aria-label='Log In']",
  claim: "xpath=//div[@role='menuitem']//div[@aria-label='Claim']",
  newClaim: "xpath=//div[@role='menuitem']//div[@aria-label='New Claim']",
  dateInput: "xpath=//input[@name='FNOLWizard-FNOLWizard_FindPolicyScreen-FNOLWizardFindPolicyPanelSet-date']",
  claimSearch: "xpath=//div[@id='FNOLWizard-FNOLWizard_FindPolicyScreen-FNOLWizardFindPolicyPanelSet-Search']",
  select: "xpath=//div[@id='FNOLWizard-FNOLWizard_FindPolicyScreen-FNOLWizardFindPolicyPanelSet-PolicyResultLV-0-selectButton']",
  next: "xpath=//div[@aria-label='Next']",
  name: "xpath=//select[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_BasicInfoScreen-PanelRow-BasicInfoDetailViewPanelDV-ReportedBy_Name']",
  person_name: "xpath=//option[@value='Person:13433']",
  selectVehicle: "xpath=//div[@role='button']//div[@aria-label='Next']",
  newStep: "xpath=//div[@role='button']//div[@aria-label='Next']",
  lossCause: "xpath=//select[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Claim_LossCause']",
  vehicleCollision: "xpath=//option[@value='vehcollision']",
  whatHappened: "xpath=//textarea[@name='FNOLWizard-FullWizardStepSet-FNOLWizard_NewLossDetailsScreen-LossDetailsAddressDV-Description']",
};

export default locators;

